/*
 * Kuha, Janne: Tehokas Java EE -sovellustuotanto. WSOY 2008,
 * www.docendo.fi.
 */
package fi.harjoitustyo.verkkokauppa.web.ehdotus;

import java.util.ArrayList;
import java.util.List;

/**
 * Suomen paikkakunnat, lähteenä käytetty Tiehallintokeskuksen
 * sivuja
 * http://alk.tiehallinto.fi/www2/valimatkat/vmpist_uusi.htm.
 * 
 * 
 * 
 * @author kuha
 * 
 */
public class PaikkakuntaEhdotus extends
    AutomaattinenEhdotuskentta {

  // Lista paikkakunnista
  private static final List<String> paikkakunnat =
      new ArrayList<String>();

  private static final long serialVersionUID = 1L;
  static {
    paikkakunnat.add("Alahärmä");
    paikkakunnat.add("Alajärvi");
    paikkakunnat.add("Alastaro");
    paikkakunnat.add("Alavieska");
    paikkakunnat.add("Alavus");
    paikkakunnat.add("Anjalankoski");
    paikkakunnat.add("Anttola");
    paikkakunnat.add("Artjärvi");
    paikkakunnat.add("Asikkala");
    paikkakunnat.add("Askainen");
    paikkakunnat.add("Askola");
    paikkakunnat.add("Aura");
    paikkakunnat.add("Dragsfjärd");
    paikkakunnat.add("Elimäki");
    paikkakunnat.add("Eno");
    paikkakunnat.add("Enonkoski");
    paikkakunnat.add("Enontekiö");
    paikkakunnat.add("Enontekiö");
    paikkakunnat.add("Espoo");
    paikkakunnat.add("Eura");
    paikkakunnat.add("Eurajoki");
    paikkakunnat.add("Evijärvi");
    paikkakunnat.add("Forssa");
    paikkakunnat.add("Haapajärvi");
    paikkakunnat.add("Haapavesi");
    paikkakunnat.add("Hailuoto");
    paikkakunnat.add("Halikko");
    paikkakunnat.add("Halsua");
    paikkakunnat.add("Hamina");
    paikkakunnat.add("Hankasalmi");
    paikkakunnat.add("Hanko");
    paikkakunnat.add("Harjavalta");
    paikkakunnat.add("Hartola");
    paikkakunnat.add("Hattula");
    paikkakunnat.add("Hauho");
    paikkakunnat.add("Haukipudas");
    paikkakunnat.add("Haukivuori");
    paikkakunnat.add("Hausjärvi");
    paikkakunnat.add("Heinola");
    paikkakunnat.add("Heinävesi");
    paikkakunnat.add("Helsinki");
    paikkakunnat.add("Himanka");
    paikkakunnat.add("Hirvensalmi");
    paikkakunnat.add("Hollola");
    paikkakunnat.add("Honkajoki");
    paikkakunnat.add("Houtskari");
    paikkakunnat.add("Huittinen");
    paikkakunnat.add("Humppila");
    paikkakunnat.add("Hyrynsalmi");
    paikkakunnat.add("Hyvinkää");
    paikkakunnat.add("Hämeenkoski");
    paikkakunnat.add("Hämeenkyrö");
    paikkakunnat.add("Hämeenlinna");
    paikkakunnat.add("Ii");
    paikkakunnat.add("Iisalmi");
    paikkakunnat.add("Iitti");
    paikkakunnat.add("Ikaalinen");
    paikkakunnat.add("Ilmajoki");
    paikkakunnat.add("Ilomantsi");
    paikkakunnat.add("Imatra");
    paikkakunnat.add("Inari");
    paikkakunnat.add("Iniö");
    paikkakunnat.add("Inkoo");
    paikkakunnat.add("Isojoki");
    paikkakunnat.add("Isokyrö");
    paikkakunnat.add("Jaala");
    paikkakunnat.add("Jalasjärvi");
    paikkakunnat.add("Janakkala");
    paikkakunnat.add("Joensuu");
    paikkakunnat.add("Jokioinen");
    paikkakunnat.add("Joroinen");
    paikkakunnat.add("Joutsa");
    paikkakunnat.add("Joutseno");
    paikkakunnat.add("Juankoski");
    paikkakunnat.add("Jurva");
    paikkakunnat.add("Juuka");
    paikkakunnat.add("Juupajoki");
    paikkakunnat.add("Juva");
    paikkakunnat.add("Jyväskylä");
    paikkakunnat.add("Jyväskylän mlk");
    paikkakunnat.add("Jämijärvi");
    paikkakunnat.add("Jämsä");
    paikkakunnat.add("Jämsä");
    paikkakunnat.add("Jämsänkoski");
    paikkakunnat.add("Jäppilä");
    paikkakunnat.add("Järvenpää");
    paikkakunnat.add("Kaarina");
    paikkakunnat.add("Kaavi");
    paikkakunnat.add("Kajaani");
    paikkakunnat.add("Kalajoki");
    paikkakunnat.add("Kalvola");
    paikkakunnat.add("Kangasala");
    paikkakunnat.add("Kangaslampi");
    paikkakunnat.add("Kangasniemi");
    paikkakunnat.add("Kankaanpää");
    paikkakunnat.add("Kannonkoski");
    paikkakunnat.add("Kannus");
    paikkakunnat.add("Karijoki");
    paikkakunnat.add("Karinainen");
    paikkakunnat.add("Karjaa");
    paikkakunnat.add("Karjalohja");
    paikkakunnat.add("Karkkila");
    paikkakunnat.add("Karstula");
    paikkakunnat.add("Karttula");
    paikkakunnat.add("Karvia");
    paikkakunnat.add("Kaskinen");
    paikkakunnat.add("Kauhajoki");
    paikkakunnat.add("Kauhava");
    paikkakunnat.add("Kauniainen");
    paikkakunnat.add("Kaustinen");
    paikkakunnat.add("Keitele");
    paikkakunnat.add("Kemi");
    paikkakunnat.add("Kemijärvi");
    paikkakunnat.add("Keminmaa");
    paikkakunnat.add("Kemiö");
    paikkakunnat.add("Kempele");
    paikkakunnat.add("Kerava");
    paikkakunnat.add("Kerimäki");
    paikkakunnat.add("Kestilä");
    paikkakunnat.add("Kesälahti");
    paikkakunnat.add("Keuruu");
    paikkakunnat.add("Kihniö");
    paikkakunnat.add("Kiihtelysvaara");
    paikkakunnat.add("Kiikala");
    paikkakunnat.add("Kiikoinen");
    paikkakunnat.add("Kiiminki");
    paikkakunnat.add("Kinnula");
    paikkakunnat.add("Kirkkonummi");
    paikkakunnat.add("Kisko");
    paikkakunnat.add("Kitee");
    paikkakunnat.add("Kittilä");
    paikkakunnat.add("Kiukainen");
    paikkakunnat.add("Kiuruvesi");
    paikkakunnat.add("Kivijärvi");
    paikkakunnat.add("Kodisjoki");
    paikkakunnat.add("Kokemäki");
    paikkakunnat.add("Kokkola");
    paikkakunnat.add("Kolari");
    paikkakunnat.add("Konnevesi");
    paikkakunnat.add("Kontiolahti");
    paikkakunnat.add("Korpilahti");
    paikkakunnat.add("Korppoo");
    paikkakunnat.add("Korsnäs");
    paikkakunnat.add("Kortesjärvi");
    paikkakunnat.add("Koski Tl");
    paikkakunnat.add("Kotka");
    paikkakunnat.add("Kouvola");
    paikkakunnat.add("Kristiinankaupunki");
    paikkakunnat.add("Kruunupyy");
    paikkakunnat.add("Kuhmalahti");
    paikkakunnat.add("Kuhmo");
    paikkakunnat.add("Kuhmoinen");
    paikkakunnat.add("Kuivaniemi");
    paikkakunnat.add("Kullaa");
    paikkakunnat.add("Kuopio");
    paikkakunnat.add("Kuorevesi");
    paikkakunnat.add("Kuortane");
    paikkakunnat.add("Kurikka");
    paikkakunnat.add("Kuru");
    paikkakunnat.add("Kustavi");
    paikkakunnat.add("Kuusamo");
    paikkakunnat.add("Kuusankoski");
    paikkakunnat.add("Kuusjoki");
    paikkakunnat.add("Kylmäkoski");
    paikkakunnat.add("Kyyjärvi");
    paikkakunnat.add("Kälviä");
    paikkakunnat.add("Kärkölä");
    paikkakunnat.add("Kärsämäki");
    paikkakunnat.add("Köyliö");
    paikkakunnat.add("Lahti");
    paikkakunnat.add("Laihia");
    paikkakunnat.add("Laitila");
    paikkakunnat.add("Lammi");
    paikkakunnat.add("Lapinjärvi");
    paikkakunnat.add("Lapinlahti");
    paikkakunnat.add("Lappajärvi");
    paikkakunnat.add("Lappeenranta");
    paikkakunnat.add("Lappi");
    paikkakunnat.add("Lapua");
    paikkakunnat.add("Laukaa");
    paikkakunnat.add("Lavia");
    paikkakunnat.add("Lehtimäki");
    paikkakunnat.add("Leivonmäki");
    paikkakunnat.add("Lemi");
    paikkakunnat.add("Lempäälä");
    paikkakunnat.add("Lemu");
    paikkakunnat.add("Leppävirta");
    paikkakunnat.add("Lestijärvi");
    paikkakunnat.add("Lieksa");
    paikkakunnat.add("Lieto");
    paikkakunnat.add("Liljendal");
    paikkakunnat.add("Liminka");
    paikkakunnat.add("Liperi");
    paikkakunnat.add("Lohja");
    paikkakunnat.add("Lohtaja");
    paikkakunnat.add("Loimaa");
    paikkakunnat.add("Loimaan kunta");
    paikkakunnat.add("Loppi");
    paikkakunnat.add("Loviisa");
    paikkakunnat.add("Luhanka");
    paikkakunnat.add("Lumijoki");
    paikkakunnat.add("Luopioinen");
    paikkakunnat.add("Luoto");
    paikkakunnat.add("Luumäki");
    paikkakunnat.add("Luvia");
    paikkakunnat.add("Längelmäki");
    paikkakunnat.add("Maalahti");
    paikkakunnat.add("Maaninka");
    paikkakunnat.add("Maksamaa");
    paikkakunnat.add("Marttila");
    paikkakunnat.add("Masku");
    paikkakunnat.add("Mellilä");
    paikkakunnat.add("Merijärvi");
    paikkakunnat.add("Merikarvia");
    paikkakunnat.add("Merimasku");
    paikkakunnat.add("Miehikkälä");
    paikkakunnat.add("Mietoinen");
    paikkakunnat.add("Mikkeli");
    paikkakunnat.add("Mikkelin mlk");
    paikkakunnat.add("Mouhijärvi");
    paikkakunnat.add("Muhos");
    paikkakunnat.add("Multia");
    paikkakunnat.add("Muonio");
    paikkakunnat.add("Mustasaari");
    paikkakunnat.add("Muurame");
    paikkakunnat.add("Muurla");
    paikkakunnat.add("Mynämäki");
    paikkakunnat.add("Myrskylä");
    paikkakunnat.add("Mäntsälä");
    paikkakunnat.add("Mänttä");
    paikkakunnat.add("Mäntyharju");
    paikkakunnat.add("Naantali");
    paikkakunnat.add("Nakkila");
    paikkakunnat.add("Nastola");
    paikkakunnat.add("Nauvo");
    paikkakunnat.add("Nilsiä");
    paikkakunnat.add("Nivala");
    paikkakunnat.add("Nokia");
    paikkakunnat.add("Noormarkku");
    paikkakunnat.add("Nousiainen");
    paikkakunnat.add("Nummi-Pusula");
    paikkakunnat.add("Nurmes");
    paikkakunnat.add("Nurmijärvi");
    paikkakunnat.add("Nurmo");
    paikkakunnat.add("Närpiö");
    paikkakunnat.add("Oravainen");
    paikkakunnat.add("Orimattila");
    paikkakunnat.add("Oripää");
    paikkakunnat.add("Orivesi");
    paikkakunnat.add("Oulainen");
    paikkakunnat.add("Oulu");
    paikkakunnat.add("Oulunsalo");
    paikkakunnat.add("Outokumpu");
    paikkakunnat.add("Padasjoki");
    paikkakunnat.add("Paimio");
    paikkakunnat.add("Paltamo");
    paikkakunnat.add("Parainen");
    paikkakunnat.add("Parikkala");
    paikkakunnat.add("Parkano");
    paikkakunnat.add("Pattijoki");
    paikkakunnat.add("Pedersören kunta");
    paikkakunnat.add("Pelkosenniemi");
    paikkakunnat.add("Pello");
    paikkakunnat.add("Perho");
    paikkakunnat.add("Pernaja");
    paikkakunnat.add("Perniö");
    paikkakunnat.add("Pertteli");
    paikkakunnat.add("Pertunmaa");
    paikkakunnat.add("Peräseinäjoki");
    paikkakunnat.add("Petäjävesi");
    paikkakunnat.add("Pieksämäki");
    paikkakunnat.add("Pieksänmaa, kesk.");
    paikkakunnat.add("Pielavesi");
    paikkakunnat.add("Pietarsaari");
    paikkakunnat.add("Pihtipudas");
    paikkakunnat.add("Piikkiö");
    paikkakunnat.add("Piippola");
    paikkakunnat.add("Pirkkala");
    paikkakunnat.add("Pohja");
    paikkakunnat.add("Polvijärvi");
    paikkakunnat.add("Pomarkku");
    paikkakunnat.add("Pori");
    paikkakunnat.add("Pornainen");
    paikkakunnat.add("Porvoo");
    paikkakunnat.add("Posio");
    paikkakunnat.add("Pudasjärvi");
    paikkakunnat.add("Pukkila");
    paikkakunnat.add("Pulkkila");
    paikkakunnat.add("Punkaharju");
    paikkakunnat.add("Punkalaidun");
    paikkakunnat.add("Puolanka");
    paikkakunnat.add("Puumala");
    paikkakunnat.add("Pyhtää");
    paikkakunnat.add("Pyhäjoki");
    paikkakunnat.add("Pyhäntä");
    paikkakunnat.add("Pyhäranta");
    paikkakunnat.add("Pyhäsalmi");
    paikkakunnat.add("Pyhäselkä");
    paikkakunnat.add("Pylkönmäki");
    paikkakunnat.add("Pälkäne");
    paikkakunnat.add("Pöytyä");
    paikkakunnat.add("Raahe");
    paikkakunnat.add("Raisio");
    paikkakunnat.add("Rantasalmi");
    paikkakunnat.add("Rantsila");
    paikkakunnat.add("Ranua");
    paikkakunnat.add("Rauma");
    paikkakunnat.add("Rautalampi");
    paikkakunnat.add("Rautavaara");
    paikkakunnat.add("Rautjärvi");
    paikkakunnat.add("Reisjärvi");
    paikkakunnat.add("Renko");
    paikkakunnat.add("Riihimäki");
    paikkakunnat.add("Ristiina");
    paikkakunnat.add("Ristijärvi");
    paikkakunnat.add("Rovaniemi");
    paikkakunnat.add("Ruokolahti");
    paikkakunnat.add("Ruotsinpyhtää");
    paikkakunnat.add("Ruovesi");
    paikkakunnat.add("Rusko");
    paikkakunnat.add("Ruukki");
    paikkakunnat.add("Rymättylä");
    paikkakunnat.add("Rääkkylä");
    paikkakunnat.add("Saari");
    paikkakunnat.add("Saarijärvi");
    paikkakunnat.add("Sahalahti");
    paikkakunnat.add("Salla");
    paikkakunnat.add("Salo");
    paikkakunnat.add("Sammatti");
    paikkakunnat.add("Sauvo");
    paikkakunnat.add("Savitaipale");
    paikkakunnat.add("Savonlinna");
    paikkakunnat.add("Savonranta");
    paikkakunnat.add("Savukoski");
    paikkakunnat.add("Seinäjoki");
    paikkakunnat.add("Sievi");
    paikkakunnat.add("Siikainen");
    paikkakunnat.add("Siikajoki");
    paikkakunnat.add("Siilinjärvi");
    paikkakunnat.add("Simo");
    paikkakunnat.add("Sipoo");
    paikkakunnat.add("Siuntio");
    paikkakunnat.add("Sodankylä");
    paikkakunnat.add("Sodankylä");
    paikkakunnat.add("Soini");
    paikkakunnat.add("Somero");
    paikkakunnat.add("Sonkajärvi");
    paikkakunnat.add("Sotkamo");
    paikkakunnat.add("Sulkava");
    paikkakunnat.add("Sumiainen");
    paikkakunnat.add("Suodenniemi");
    paikkakunnat.add("Suolahti");
    paikkakunnat.add("Suomenniemi");
    paikkakunnat.add("Suomusjärvi");
    paikkakunnat.add("Suomussalmi");
    paikkakunnat.add("Suonenjoki");
    paikkakunnat.add("Sysmä");
    paikkakunnat.add("Säkylä");
    paikkakunnat.add("Särkisalo");
    paikkakunnat.add("Taipalsaari");
    paikkakunnat.add("Taivalkoski");
    paikkakunnat.add("Taivassalo");
    paikkakunnat.add("Tammela");
    paikkakunnat.add("Tammisaari");
    paikkakunnat.add("Tampere");
    paikkakunnat.add("Tarvasjoki");
    paikkakunnat.add("Temmes");
    paikkakunnat.add("Tervo");
    paikkakunnat.add("Tervola");
    paikkakunnat.add("Teuva");
    paikkakunnat.add("Tohmajärvi");
    paikkakunnat.add("Toholampi");
    paikkakunnat.add("Toijala");
    paikkakunnat.add("Toivakka");
    paikkakunnat.add("Tornio");
    paikkakunnat.add("Turku");
    paikkakunnat.add("Tuulos");
    paikkakunnat.add("Tuupovaara");
    paikkakunnat.add("Tuusniemi");
    paikkakunnat.add("Tuusula");
    paikkakunnat.add("Tyrnävä");
    paikkakunnat.add("Töysä");
    paikkakunnat.add("Ullava");
    paikkakunnat.add("Ulvila");
    paikkakunnat.add("Urjala");
    paikkakunnat.add("Utajärvi");
    paikkakunnat.add("Utsjoki");
    paikkakunnat.add("Uukuniemi");
    paikkakunnat.add("Uurainen");
    paikkakunnat.add("Uusikaarlepyy");
    paikkakunnat.add("Uusikaupunki");
    paikkakunnat.add("Vaala");
    paikkakunnat.add("Vaasa");
    paikkakunnat.add("Vahto");
    paikkakunnat.add("Valkeakoski");
    paikkakunnat.add("Valkeala");
    paikkakunnat.add("Valtimo");
    paikkakunnat.add("Vammala");
    paikkakunnat.add("Vampula");
    paikkakunnat.add("Vantaa");
    paikkakunnat.add("Varkaus");
    paikkakunnat.add("Varpaisjärvi");
    paikkakunnat.add("Vehkalahti");
    paikkakunnat.add("Vehmaa");
    paikkakunnat.add("Vehmersalmi");
    paikkakunnat.add("Velkua");
    paikkakunnat.add("Vesanto");
    paikkakunnat.add("Vesilahti");
    paikkakunnat.add("Veteli");
    paikkakunnat.add("Vieremä");
    paikkakunnat.add("Vihanti");
    paikkakunnat.add("Vihti");
    paikkakunnat.add("Viiala");
    paikkakunnat.add("Viitasaari");
    paikkakunnat.add("Viljakkala");
    paikkakunnat.add("Vilppula");
    paikkakunnat.add("Vimpeli");
    paikkakunnat.add("Virolahti");
    paikkakunnat.add("Virrat");
    paikkakunnat.add("Virtasalmi");
    paikkakunnat.add("Vuolijoki");
    paikkakunnat.add("Vähäkyrö");
    paikkakunnat.add("Värtsilä");
    paikkakunnat.add("Västanfjärd");
    paikkakunnat.add("Vöyri");
    paikkakunnat.add("Ylihärmä");
    paikkakunnat.add("Yli-Ii");
    paikkakunnat.add("Ylikiiminki");
    paikkakunnat.add("Ylistaro");
    paikkakunnat.add("Ylitornio");
    paikkakunnat.add("Ylivieska");
    paikkakunnat.add("Ylämaa");
    paikkakunnat.add("Yläne");
    paikkakunnat.add("Ylöjärvi");
    paikkakunnat.add("Ypäjä");
    paikkakunnat.add("Äetsä");
    paikkakunnat.add("Ähtäri");
    paikkakunnat.add("Äänekoski");
  }

  /**
   * Konstruktori, jossa asetetaan komponentin tunniste.
   * 
   * @param id
   */
  public PaikkakuntaEhdotus(final String komponentinId) {
    super(komponentinId);

  }

  /**
   * Palauttaa listan syötteeseen sopivista vaihtoehdoista.
   */
  @Override
  public List<String> getVaihtoehdot(final String syote) {
    final List<String> tulokset = new ArrayList<String>();
    // Mikäli lähdejoukon alkion nimi vastaa annettua syötettä
    // lisätään kyseinen alkio osaksi tuloslistaa.
    for (String vaihtoehto : paikkakunnat) {
      String vaihtoehtoMj = vaihtoehto.toLowerCase();
      String verrattavaMj = syote.toLowerCase();
      if (vaihtoehtoMj.contains(verrattavaMj)) {
        tulokset.add(vaihtoehto);
      }
    }

    return tulokset;
  }

}
